### ISSUE TITLE
Nu se pate edita campul de la Stakeholders and Interests

### ISSUE THREAD

**Issue by qazwer1** [IngineriaProgramariiGrupaA7/view1#14]
Pasi:
1. deschide browser
2. tasteaza url (localhost:8080)
3. click Create 
4. click Stakeholders and Interests
5. click ADD
6. tasteaza text
7. click Edit

Rezultat dorit:
Textul salvat din casutatext nou adaugata permite modificarea lui, printr-un click de mouse pentru a fi selectat

Actualul rezultat:
Nu se pate edita campul de la Stakeholders and Interests

**Comment by radu-solca** [comment]
Editarea merge bine on my end.
Numele actionarului se modifica prin popup-ul ce apare in urma unui click pe "EDIT".

**Comment by qazwer1** [comment]
Mai verific si eu o data si daca totul merge inchidem bugul

**Comment by qazwer1** [comment]
Rezolvat
