### ISSUE TITLE
Cand se apasa butonul SAVE DRAFT iti salveaza un fisier "draft.json" in calculator

### ISSUE THREAD

**Issue by qazwer1** [IngineriaProgramariiGrupaA7/view1#18]
Steps:
1. Deschide Browser
2. Introdu url-ul: "localhost:8080"
3. Apasa pe butonul create.
4. Apasa pe tabul "Title"
5. In fieldul "Insert title here" introdu un titlu
6. Apasa pe tabul "Authors"
7. In fieldul "Insert author name here" introdu un autor
8. Apasa pe tabul "Description"
9. In campul text "Insert description here" introdu o descriere
10. Apasa pe tabul "Domain"
11. In campul text "Insert Domain here" introdu un domeniu
12. Apasa pe tabul "Stakeholders and Interests"
13. Apasa pe butonul "Edit"
14. In fereastra noua deschisa in fieldul "Stakeholder title" introdu un titlu
15. In campul text "Stakeholder interests" introdu un text
16. Apasa pe butonul "SAVE"
17. Apasa pe tabul "Actors and Objectives"
18. Apasa pe butonul "Edit"
19. In fereastra noua deschisa, in fieldul "Actor name" introdu un nume de actor
20 In campul text "Objectives" introdu obiective
21 Daca exista 2 actori si al doilea mosteneste ceva de la primul, se va selecta din comboboxul "Inherits"
22. Apasa pe butonul "Save"
23. Apasa pe tabul "Usecases"
24. Apasa pe butonul "Edit"
25. In fereastra nou deschisa in fieldul "Use-case title" introdu un titlu pentru usecase
26. In campul text "Objective/Context" introdu obiective
27. Din comboboxul "Actors" selecteaza actor
28. Daca exista mai multi actori apasa pe butonul "ADD" si repeta procedura de la puntul 27
29. In fieldul "Step title" introdu titlu pentru pasi
30. In campul text "Description" introdu o descriere
31. Daca sunt mai multi pasi se apasa pe butonul "ADD" si se repeta pasii de la puntele 29, 30
32. Daca exista extensie se adauga din comboboxul "Extensions"
33. In fieldul "Extension title" se adauga un titlu de extensie
34. in campul text "Description" se va introduce o descriere
35. Daca sunt mai multe extensii se apasa pe butonul "ADD" si se repeta pasii de la punctele 32, 33, 34
36. Din comboboxurile de la "Relationship" se vor selecta relatiile necesare.
37. Daca sunt mai multe relatii se apasa pe butonul "ADD" si se repeta pasul 36
38. Apasa pe butonul "Save"
39. Apasa pe butonul "SAVE DRAFT"

Actual Results:
Cand se apasa butonul SAVE DRAFT iti salveaza un fisier "draft.json" in calculator

Expected Results:
Cand se apasa butonul SAVE DRAFT fisierul "draft.json" ar trebui sa fie salvat in rootul proiectului sau creat un folder in case se vor salva toate drafturile.

**Comment by mariaanghelachee** [comment]
Asta trebuie sa faca butonul Save Draft sa iti salveze la tine pe calculator json-ul ala

**Comment by teodorachiosa** [comment]
Clientul salveaza fisierul ala in functie de setarile browserului (poate are ca default in 'Downloads' sau 'Ask where to save').

**Comment by qazwer1** [comment]
ok este precizat in documentatie? Nu am observat.

**Comment by radu-solca** [comment]
Nu cred ca e precizat fiindca abia azi am implementat asa; o sa actualizam. Our bad.
